server:
  port: 8086
spring:
  application:
    name: mall-page-web
  thymeleaf:
    cache: false
    encoding: UTF-8
  main:
    allow-bean-definition-overriding: true

#页面生成存储路径
pagepath: D:/pages/items/

#页面生成存储路径
seckillpath: D:/pages/seckillitems/

#日志配置
logging:
  pattern:
    console: "%msg%n"