server:
  port: 8083

spring:
  application:
    name: mall-canal
  main:
    allow-bean-definition-overriding: true

#Canal配置
canal:
  server: 192.168.100.130:11111
  destination: example
#日志配置
logging:
  pattern:
    console: "%msg%n"
  level:
    root: error